@echo off
start cmd /c "python main.py --logic Taski --email=your_email9999@example.com --name=taski --password=your_password --team etimo"
start cmd /c "python main.py --logic Random --email=test4@email.com --name=stima4 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test5@email.com --name=stima5 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test6@email.com --name=stima6 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Random --email=test7@email.com --name=stima7 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Nopal2 --email=nopal2@example.com --name=nopal2 --password=your_password --team etimo" 
@REM start cmd /c "python main.py --logic Nopal3 --email=nopal3@example.com --name=nopal3 --password=your_password --team etimo" 
@REM start cmd /c "python main.py --logic Nopal --email=your_email999@example.com --name=nopal --password=your_password --team etimo"
@REM start cmd /c "python main.py --logic Nopal4 --email=nopal4@example.com --name=nopal4 --password=your_password --team etimo" 
@REM start cmd /c "python main.py --logic Nopal5 --email=nopal5@example.com --name=nopal5 --password=your_password --team etimo" 
start cmd /c "python main.py --logic Nopal7 --email=nopal7@example.com --name=nopal7 --password=your_password --team etimo" 
@REM start cmd /c "python main.py --logic Nopal9 --email=nopalteleport@example.com --name=teleport --password=teleport --team etimo" 
@REM start cmd /c "python main.py --logic Nopal9 --email=nopal9@example.com --name=nopal9 --password=your_password --team etimo" 
start cmd /c "python main.py --logic Nopal8 --email=nopal8@example.com --name=nopal8 --password=your_password --team etimo" 
@REM start cmd /c "python main.py --logic draftTele --email=drafttele@example.com --name=drafttele --password=your_passwordtele --team etimo" 
start cmd /c "python main.py --logic NB --email=nanangboneng9@example.com --name=NaBon --password=nanang12345 --team etimo" 
start cmd /c "python main.py --logic NB --email=nanangboneng135@example.com --name=Nanang --password=nanang135 --team etimo" 
