@echo off
@REM start cmd /c "python main.py --logic Taski --email=tazkia@email.com --name=taskiBaru --password=312213 --team etimo"
@REM start cmd /c "python main.py --logic Taski2 --email=tazki2@email.com --name=taskiLama --password=123456 --team etimo"
start cmd /c "python main.py --logic Tele --email=daresha@email.com --name=Ida --password=105702 --team etimo"
start cmd /c "python main.py --logic Tele --email=va@roputja.ca --name=Chase --password=316109 --team etimo"
start cmd /c "python main.py --logic Tele --email=tivsovtur@ja.bf --name=Sadie --password=374184 --team etimo"
start cmd /c "python main.py --logic Tele --email=aro@tavag.pl --name=Hettie --password=125679 --team etimo"
@REM start cmd /c "python main.py --logic NB --email=votsek@ogeje.sm --name=Johnny --password=325178 --team etimo"
@REM start cmd /c "python main.py --logic NB --email=hu@etletlob.sk --name=Gilbert --password=305731 --team etimo"
@REM start cmd /c "python main.py --logic  --email=todizhet@email.com --name=Johnny --password=180534 --team etimo"
@echo off
@REM start cmd /c "python main.py --logic Taski3 --email=tatang@email.com --name=HindarTele --password=13522032 --team etimo"
@REM start cmd /c "python main.py --logic Taski3 --email=cuw@sac.ss --name=Edwin --password=10826 --team etimo"
@REM start cmd /c "python main.py --logic Taski3 --email=cu@tiptu.ls --name=Antonio --password=64255 --team etimo"
@REM start cmd /c "python main.py --logic Taski3 --email=atkupo@mawooc.co.uk --name=Bruce --password=145231 --team etimo"
@REM start cmd /c "python main.py --logic Taski3 --email=dagew@faricike.tz --name=Mario --password=137277 --team etimo"
@REM @REM start cmd /c "python main.py --logic Nopal --email=hu@nul.ag --name=Tom --password=463615 --team etimo"
@REM @REM start cmd /c "python main.py --logic Nopal --email=kaopag@fav.gs --name=Harriet --password=184874 --team etimo"
@REM @REM start cmd /c "python main.py --logic Nopal --email=zashezu@iholip.ht --name=Terry --password=22036 --team etimo"
@REM @REM start cmd /c "python main.py --logic Nopal --email=ti@ageomesu.yt --name=Nathan --password=994484 --team etimo"
@REM @REM start cmd /c "python main.py --logic Nopal --email=fuzitge@tehuniku.nc --name=Justin --password=66 --team etimo"
@REM start cmd /c "python main.py --logic Taski4 --email=asddsa@keartu.mr --name=kain --password=12323123 --team etimo"